const UserRouter = require("./UserRouter");
const StaffRouter = require("./StaffRouter");
const CategoryFood = require("./CategoryFood");
const CategoryMenu = require("./CategoryMenu");
const CategoryIngredient = require("./CategoryIngredient");
const Food = require("./FoodRouter");
const Menu = require("./MenuRouter");
const Ingredient = require("./IngredientRouter");
const CategoryTable = require("./CategoryTable");
const Supplier = require("./Supplier");
const Customer = require("./Customer");
const Booking = require("./Booking");
const Recipe = require("./Recipe");
const Order = require("./Order");
const Bill = require("./Bill");
const Combo = require("./Combo");
const Report = require("./Report");
const Upload = require("./UploadRouter");
const Role = require("./RoleRouter");
const Permission = require("./Permission");
const Table = require("./Table");
const Area = require("./Area");
const CategoryBanner = require("./CategoryBanner");
const Banner = require("./Banner");
const CategoryGallery = require("./CategoryGallery");
const Gallery = require("./Gallery");
const Blog = require("./Blog");
const Infor = require("./Infor");

const routes = (app) => {
  app.use("/api/user", UserRouter);
  app.use("/api/staff", StaffRouter);
  app.use("/api/blog", Blog);
  app.use("/api/infor", Infor);
  app.use("/api/banner", Banner);
  app.use("/api/gallery", Gallery);
  app.use("/api/category-food", CategoryFood);
  app.use("/api/category-menu", CategoryMenu);
  app.use("/api/category-ingredient", CategoryIngredient);
  app.use("/api/category-banner", CategoryBanner);
  app.use("/api/category-gallery", CategoryGallery);
  app.use("/api/food", Food);
  app.use("/api/menu", Menu);
  app.use("/api/ingredient", Ingredient);
  app.use("/api/category-table", CategoryTable);
  app.use("/api/table", Table);
  app.use("/api/area", Area);
  app.use("/api/supplier", Supplier);
  app.use("/api/customer", Customer);
  app.use("/api/booking", Booking);
  app.use("/api/recipe", Recipe);
  app.use("/api/order", Order);
  app.use("/api/bill", Bill);
  app.use("/api/combo", Combo);
  app.use("/api/report", Report);
  app.use("/api/role", Role);
  app.use("/api/permission", Permission)
  app.use("/api/upload", Upload);
};

module.exports = routes;
